# Services. Listed in order.
# Fields:
#   title   (required)

- title: "<a href=\"https://2026.eurosys.org/shadow-program-committee.html#pc\">EUROSYS '26 Shadow Program Committee Member</a>"
- title: "<a href=\"https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=11434833\">IEEE Transactions on Dependable and Secure Computing (TDSC '25) Reviewer</a>"
- title: "Thirty-Fourth International Joint Conference on Artificial Intelligence (IJCAI '25) Emergency Reviewer"
