# Services. Listed in order.
# Fields:
#   title   (required)

- title: "<a href=\"https://2026.eurosys.org/shadow-program-committee.html#pc\">EUROSYS '26 Shadow Program Committee Member</a>"
- title: "<a href=\"https://www.webofscience.com/wos/author/record/MFJ-5385-2025\">IEEE Transactions on Dependable and Secure Computing (TDSC) Reviewer</a>"
- title: "Thirty-Fourth International Joint Conference on Artificial IntelligenceInternational (IJCAI '25) Emergency Reviewer"
